name: Node.js CI

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test-ci

  release:
    needs: build
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
